-- Run this once in the Supabase SQL Editor.
-- Only a daily, one-way visitor fingerprint is stored. Raw IP addresses never
-- leave the Next.js server.

create table if not exists public.portfolio_visits (
  id bigint generated by default as identity primary key,
  visitor_hash text not null,
  visited_on date not null default (timezone('Asia/Manila', now()))::date,
  created_at timestamptz not null default now(),
  constraint portfolio_visits_daily_unique unique (visitor_hash, visited_on)
);

-- Keep an existing installation aligned when this script is rerun.
alter table public.portfolio_visits
  alter column visited_on
  set default (timezone('Asia/Manila', now()))::date;

alter table public.portfolio_visits enable row level security;

-- Browser clients receive no table access. The Next.js route calls this with
-- the server-only secret key, which uses the service_role and bypasses RLS.
revoke all on table public.portfolio_visits from anon, authenticated;

create or replace function public.record_portfolio_visit(p_visitor_hash text)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  total_visits bigint;
begin
  if p_visitor_hash is null or length(p_visitor_hash) <> 64 then
    raise exception 'Invalid visitor hash';
  end if;

  insert into public.portfolio_visits (visitor_hash)
  values (p_visitor_hash)
  on conflict (visitor_hash, visited_on) do nothing;

  select count(*) into total_visits from public.portfolio_visits;
  return total_visits;
end;
$$;

revoke all on function public.record_portfolio_visit(text) from public, anon, authenticated;
grant execute on function public.record_portfolio_visit(text) to service_role;
